from random import randint
'''
Author: Shreejan Shrestha
Date: 8/13/2020
Purpose: Two player number guessing game. Both players will give one number each to the computer. After assigning the values
the computer will generate the number which is in-between those two values. blablabla...
'''

def comp_gen(first_player,second_player):
    # guess made my computer
    comp_gen = randint(first_player, second_player)
    return comp_gen

def players(comp_gen):
    print("Player 1 turn to guess the number")
    # counting the chances player one took to guess the number
    # pone means playerone
    pone_count = 0
    while True:
        try:
            pone_guess = int(input("Guess the number:"))
            pone_count += 1

            if pone_guess == comp_gen:
                print(f"\tPlayer one took {pone_count} chance(s) to guess the number.")
                break
            elif pone_guess < comp_gen:
                print(
                    "\tYour guess is lesser than the number generated by the computer. Try with greater value number.")
                continue
            else:
                print(
                    "\tYour guess is greater than the number generated by the computer. Try with lesser value number.")
                continue

        except Exception as e:
            print('\n\t\t\twarning!!!\nYour input must be a integer value\n'.upper())
            continue


    # using for loop to print * so that the result will go up and player two won't be able to see the value
    for i in range(20):
        print('*')
    print(f"Player one took {pone_count} chance(s) to guess the number.")
    print("Player two turn to guess the number.")
    ptwo_count = 0
    while True:
        try:
            ptwo_guess = int(input("Guess the number:"))
            ptwo_count += 1
            if ptwo_guess == comp_gen:
                print(f"\tPlayer one took {ptwo_count} chance(s) to guess the number.")
                break
            elif ptwo_guess < comp_gen:
                print(
                    "\tYour guess is lesser than the number generated by the computer. Try with greater value number.")
                continue
            else:
                print(
                    "\tYour guess is greater than the number generated by the computer. Try with lesser value number.")
                continue
        except Exception as e:
            print('\n\t\t\twarning!!!\nYour input must be a integer value\n'.upper())
            continue


    if pone_count > ptwo_count:
        print("\nPlayer two won")
    else:
        print("\nPlayer one won")



if __name__ == '__main__':
    print("Let's not give the value more than 100 for now, or else it will take ages to finish this game.")
    first_player = int(input("Give your number:"))
    second_player = int(input("Give your number:"))
    print(f'\nPlayer one has set the number {first_player} whereas player two has set {second_player}.'
          f' Now guess any number from {first_player} to {second_player}.\n')
    g=comp_gen(first_player, second_player)
    players(g)








