from random import randint
'''
Author: Shreejan Shrestha
Date: 8/13/2020
Purpose: Two player number guessing game. Both players will give one number each to the computer. After assigning the values
the computer will generate the number which is in-between those two values. blablabla...
'''

def comp_gen(first_player,second_player):
    # guess made my computer
    comp_gen = randint(first_player, second_player)
    
    return comp_gen

def game(comp_gen):

    # counting the chances player one took to guess the number
    time_count = 0
    while True:
        try:
            guess = int(input("Guess the number:"))
            time_count += 1

        except Exception as e:
            print('\n\t\t\twarning!!!\nYour input must be a integer value\n'.upper())
            continue
        else:
            if guess == comp_gen:
                print(f"\tPlayer one took {time_count} chance(s) to guess the number.")

                break
            elif guess < comp_gen:

                print(
                    "\tYour guess is lesser than the number generated by the computer. Try with greater value number.")
                continue
            else:

                print(
                    "\tYour guess is greater than the number generated by the computer. Try with lesser value number.")
                continue
    return time_count

if __name__ == '__main__':
    print("Let's not give the value more than 100 for now, or else it will take ages to finish this game.")
    first_player = int(input("Player1 give your number:"))
    second_player = int(input("Player2 give your number:"))
    print(f'\nPlayer one has set the number {first_player} whereas player two has set {second_player}.'
          f' Now guess any number from {first_player} to {second_player}.\n')

    g1 = comp_gen(first_player, second_player)

    player1 = game(g1)
    # using for loop to print * so that the result will go up and player two won't be able to see the value
    for i in range(20):
        print('*')
    print(f"Player one took {player1} chance(s) to guess the number.")
    print("Player two turn to guess the number.")
    g2 = comp_gen(first_player, second_player)
    player2 = game(g2)
    print(f'Computer generated {g1} for player1 and {g2} for player2')
    if player1 > player2:
        print("\nPlayer2 won.")
    elif player1 == player2:
        print(f"Game is tie as both player guessed in {player1} time(s).")
    else:
        print("\nPlayer1 won.")









